global:
  resolve_timeout: 1m # When an alert resolves, wait 1 minute before marking it resolved.

route:
  receiver: "default-receiver" # Where alerts should go by default.
  group_wait: 10s # Wait 10s before grouping and sending alerts.
  group_interval: 5m # If an alert is already sent, wait 5 min before sending another from same group.
  repeat_interval: 1h # If alert persists, resend every 1 hour.

receivers:
  - name: "default-receiver"
    webhook_configs:
      - url: "http://localhost:5001/" # Placeholder URL (no real webhook).
